steps:
  # Build your Symfony app image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/symfony-app', '.']

  # Push it to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/symfony-app']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'symfony-app',
        '--image', 'gcr.io/$PROJECT_ID/symfony-app',
        '--region', 'europe-west4',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]

  # Optional: Clean up old images (uncomment if you want)
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       gcloud container images list-tags gcr.io/$PROJECT_ID/symfony-app --sort-by=TIMESTAMP \
  #       | tail -n +6 | awk '{print $1}' | xargs -r -n1 gcloud container images delete -q --force-delete-tags

options:
  logging: CLOUD_LOGGING_ONLY
