steps:
  # Build your Symfony app image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/symfony-app', '.']

  # Push it to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/symfony-app']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'symfony-app',
        '--image', 'gcr.io/$PROJECT_ID/symfony-app',
        '--region', 'europe-west4',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]
